version: '3.7'

services:
  # Database
  db:
    image: mysql:8.0.19
    volumes:
      - db_data:/var/lib/mysql
    #restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      #MYSQL_DATABASE: wordpress
      MYSQL_USER: becky
      MYSQL_PASSWORD: beckypassword
    ports:
      - '3306:3306'
    networks:
      - becky
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    #restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword 
    networks:
      - becky
networks:
  becky:
volumes:
  db_data: