"""empty message

Revision ID: 2218c5c46b85
Revises: 7f2f8596a7f5
Create Date: 2020-05-09 20:00:57.554002

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2218c5c46b85'
down_revision = '7f2f8596a7f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('public_id', table_name='customer')
    op.drop_table('customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('custID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('public_id', mysql.VARCHAR(charset='latin1', collation='latin1_swedish_ci', length=50), nullable=True),
    sa.Column('username', mysql.VARCHAR(charset='latin1', collation='latin1_swedish_ci', length=255), nullable=False),
    sa.Column('passwordHash', mysql.VARCHAR(charset='latin1', collation='latin1_swedish_ci', length=255), nullable=False),
    sa.Column('name', mysql.VARCHAR(charset='latin1', collation='latin1_swedish_ci', length=255), nullable=False),
    sa.Column('email', mysql.VARCHAR(charset='latin1', collation='latin1_swedish_ci', length=255), nullable=False),
    sa.Column('address', mysql.VARCHAR(charset='latin1', collation='latin1_swedish_ci', length=255), nullable=False),
    sa.Column('member', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('custID'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('public_id', 'customer', ['public_id'], unique=True)
    # ### end Alembic commands ###
