"""empty message

Revision ID: 2e8080e5ae35
Revises: 7fbfa0b5c05d
Create Date: 2020-05-02 19:27:01.504656

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2e8080e5ae35'
down_revision = '7fbfa0b5c05d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('username', table_name='user_profiles')
    op.drop_table('user_profiles')
    op.alter_column('customer', 'public_id',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_swedish_ci', length=50),
               nullable=True)
    op.create_unique_constraint(None, 'customer', ['public_id'])
    op.create_index(op.f('ix_items_ordID'), 'items', ['ordID'], unique=False)
    op.alter_column('manager', 'public_id',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_swedish_ci', length=50),
               nullable=True)
    op.create_unique_constraint(None, 'manager', ['public_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'manager', type_='unique')
    op.alter_column('manager', 'public_id',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_swedish_ci', length=50),
               nullable=False)
    op.drop_index(op.f('ix_items_ordID'), table_name='items')
    op.drop_constraint(None, 'customer', type_='unique')
    op.alter_column('customer', 'public_id',
               existing_type=mysql.VARCHAR(charset='latin1', collation='latin1_swedish_ci', length=50),
               nullable=False)
    op.create_table('user_profiles',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('last_name', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('username', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('username', 'user_profiles', ['username'], unique=True)
    # ### end Alembic commands ###
