"""empty message

Revision ID: 65783f5f0044
Revises: 2e8080e5ae35
Create Date: 2020-05-07 22:20:46.567364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65783f5f0044'
down_revision = '2e8080e5ae35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
    sa.Column('cID', sa.Integer(), nullable=False),
    sa.Column('custID', sa.Integer(), nullable=True),
    sa.Column('bookID', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('cID')
    )
    op.create_table('promotions',
    sa.Column('pID', sa.Integer(), nullable=False),
    sa.Column('percoff', sa.Float(asdecimal=True), nullable=False),
    sa.PrimaryKeyConstraint('pID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('promotions')
    op.drop_table('cart')
    # ### end Alembic commands ###
