"""empty message

Revision ID: 7f2f8596a7f5
Revises: 65783f5f0044
Create Date: 2020-05-08 22:39:22.060202

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7f2f8596a7f5'
down_revision = '65783f5f0044'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('pwd_hash', sa.String(length=200), nullable=True),
    sa.Column('urole', sa.String(length=80), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('member', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.drop_index('public_id', table_name='manager')
    op.drop_table('manager')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manager',
    sa.Column('manID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('passwordHash', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('public_id', mysql.VARCHAR(charset='latin1', collation='latin1_swedish_ci', length=50), nullable=True),
    sa.PrimaryKeyConstraint('manID'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('public_id', 'manager', ['public_id'], unique=True)
    op.drop_table('user')
    # ### end Alembic commands ###
